# CmdPlus
#
# Permissions:
# Create cmdsigns: cmdsign.create
# Alias permissions: in aliases.yml!!
#
#
  // fix cmdplus reload config (not reloading)
settings:
  cmd_cooldown: 1s # s = second | m = minute
  language: EN # Default language. check the lang folder for available languages | Some translations may not be accurated! please let me know which are not so i can fix this in the next update.
  cmdsign_cooldown: 3s
  plugin_prefix: "&7[&6CmdPlus&7]"