name: CmdPlus
version: v5.0-BETA
main: me.JuliusH_1.cmdplus
softdepend: [PlaceholderAPI]
api-version: 1.21
authors: [ JuliusH_1 | Owner VoidCraft Network ]
description: Create custom command aliases command signs and much much more!
website: www.voidcraftmc.net
commands:
  cmdalias:
    description: Command alias management
    usage: /cmdalias <create/list> <alias> <command> [permission]
    permission: commandalias.manage
  cmdplus:
    description: CmdPlus management
    usage: /cmdplus reload <alias/sign/config/all>
    permission: cmdplus.manage
  ban:
    description: Bans a player
  mute:
    description: Mutes a player
  kick:
    description: Kicks a player
  trash:
    description: Opens a trash bin to dispose of items
  bin:
    description: Opens a trash bin to dispose of items
  privatechest:
    description: Opens a private chest