# CmdPlus
#
# Permissions:
# Create cmdsigns: cmdsign.create
# Alias permissions: in aliases.yml!!
#
settings:
  cmd_cooldown: 1s # s = second | m = minute
  language: EN # Default language. check the lang folder for available languages | Some translations may not be accurate! please let me know which are not so I can fix this in the next update.
  cmdsign_cooldown: 10s
  plugin_prefix: "&7[&6CmdPlus&7] " # add a space at the end of the prefix. NEEDS A RESTART TO AFFECT THE MESSAGES