name: CmdPlus
version: 5.0-BETA
main: me.JuliusH_1.cmdplus
softdepend: [PlaceholderAPI]
api-version: 1.21
authors: [ JuliusH_1 | Owner VoidCraft Network ]
description: Create custom command aliases command signs and much much more!
website: www.voidcraftmc.net
commands:
  cmdalias:
    description: Command alias management
    usage: /cmdalias <create/list> <alias> <command> [permission]
    permission: commandalias.manage
  cmdplus:
    description: CmdPlus management
    usage: /cmdplus reload <alias/sign/config/all>
    permission: cmdplus.manage
  ban:
    description: "Ban a player"
    usage: "/ban <player> <time> <reason>"
    permission: "cmdplus.ban"
  mute:
    description: "Mute a player"
    usage: "/mute <player> <time> <reason>"
    permission: "cmdplus.mute"
  kick:
    description: "Kick a player"
    usage: "/kick <player> <reason>"
    permission: "cmdplus.kick"
  tempban:
    description: "Temporarily ban a player"
    usage: "/tempban <player> <time> <reason>"
    permission: "cmdplus.tempban"
  tempmute:
    description: "Temporarily mute a player"
    usage: "/tempmute <player> <time> <reason>"
    permission: "cmdplus.tempmute"